---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu", "Pop!_OS"]

  - name: install apache2 packages
    apt:
      name: apache2
    when: ansible_distribution in ["Debian", "Ubuntu", "Pop!_OS"]


  - name: add php support for apache
    apt:
      name: libapache2-mod-php
    when: ansible_distribution in ["Debian", "Ubuntu", "Pop!_OS"]
