---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu", "Pop!_OS"]

  - name: install apache2 & PHP packages for Ubuntu flavours
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu", "Pop!_OS"]

  - name: update repository index for Fedora
    dnf:
      update_cache: yes
    when: ansible_distribution == "Fedora"

  - name: install httpd & php packages for Fedora/CentOS
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Fedora"
