---

- hosts: all
  become: true
  tasks:

  - name: install apache2 & PHP packages, and update repository index for Ubuntu flavours
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu", "Pop!_OS"]

  - name: install httpd & php packages, and update repository index for Fedora/CentOS
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Fedora"
