---
- hosts: all
  become: true

  tasks:

  - name: check status of services
    command: systemctl status "{{ item }}"
    with_items:
    - mariadb
    - firewalld
    - httpd
    - vsftpd
    - sshd
    register: service_state
    ignore_errors: yes

  - name: display service state
    debug:
      var: service_state
