---

- hosts: all
  become: true
  tasks:

  - name: install apache2 & PHP packages, and update repository index using variables and package module
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
